### PR TITLE
Jf activity from profile

### PR DESCRIPTION
**Pull request by javifr**

### CODE REVIEW

**Comment by stramel** [comment]
So many additions yet so little description in commit messages. @davidlgj @Dervisevic Should these be squashed into one descriptive commit message? 

:+1: for creating an Ionic decorator. I assume @davidlgj or @Dervisevic will take a look into it soon. I will take a look this weekend as well.

**Comment by javifr** [comment]
Excuse me guys, I created the pull request by mistake.

Is a repo that i use for ionic decorators, but is far from being mergeable.

Regards!

On Thu, May 14, 2015 at 8:55 PM, Michael Stramel <notifications@github.com>
wrote:

> So many additions yet so little description in commit messages. @davidlgj
> <https://github.com/davidlgj> @Dervisevic <https://github.com/Dervisevic>
> Should these be squashed into one descriptive commit message?
>
> [image: :+1:] for creating an Ionic decorator. I assume @davidlgj
> <https://github.com/davidlgj> or @Dervisevic
> <https://github.com/Dervisevic> will take a look into it soon. I will
> take a look this weekend as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/pull/390#issuecomment-102134736>
> .
>



-- 

Javi Fernández

**Comment by Dervisevic** [comment]
Oh, yeah i was wondering about that. It's gonna be exciting to see a new decorator! Should we close this one and you make a new one when it's ready?

**Comment by javifr** [comment]
Sure!



On Fri, May 15, 2015 at 7:33 AM, Denis Dervisevic <notifications@github.com>
wrote:

> Oh, yeah i was wondering about that. It's gonna be exciting to see a new
> decorator! Should we close this one and you make a new one when it's ready?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/pull/390#issuecomment-102264395>
> .
>



-- 

Javi Fernández

**Comment by davidlgj** [comment]
@javifr what a teaser! ;) Just ping us on gitter if you need any help

**Comment by javifr** [comment]
Glad to hear that! Because I'll need help for sure.

For now it has some patches allowing us to do some things in production, for example this:
captura de pantalla 2015-05-15 a las 10 18 09

I'll try to find time next week and make it a bit cleaner so I can issue a pull request.

Thanks for the interest!

**Comment by davidlgj** [comment]
Looks awesome!

**Comment by Dervisevic** [comment]
:+1:

**Pull request closed without merging**
