### PR TITLE
Don't override readonly if specified on items individually

### PR DESCRIPTION
**Pull request by qstrahl**
I ran into this nasty piece of behaviour introduced (I assume) by #108.

@davidlgj since you worked on that PR I'm pulling you in here. First time contributing to this project, what do you need from me to get this pushed out? My work is currently blocked by this so I can spare all the time and effort in the world.

### CODE REVIEW

**Comment by davidlgj** [comment]
Hi @qstrahl and thanks for the PR!

I merged it into the development branch and it will come out with the next release.  Next time please base do the PR against the development branch instead of master, that way it's a faster merge for us :-) Checkout the [README.md on contributing](https://github.com/Textalk/angular-schema-form/#contributing)

**Comment by qstrahl** [comment]
Ah, okay, thank you. By the way, if you're not aware, you can put
contribution information in CONTRIBUTING.md and GitHub will make a point to
present it to people making pull requests against the project.

**Comment by Dervisevic** [comment]
Oh sweet didn't know that. Well make one of those.

**Comment by davidlgj** [comment]
Cool, I didn't know that. Thanks for the tip!

sön 25 jan 2015 14:43 Denis Dervisevic <notifications@github.com> skrev:

**Pull request merged**
