### PR TITLE
Field IDs Patch

### PR DESCRIPTION
**Pull request by plong0**
Updates name and ids (along with corresponding label for="..." attributes) to use the full key (hyphen-delimited) rather than only the last piece.
If a parent FormController is found, we prepend the form's name onto the id values.

We also append the hyphen-delimited key to form.htmlClass, allowing styling of specific fields without having to manually set an htmlClass for each field.

### CODE REVIEW

**Comment by plong0** [comment]
looks like tests fail because input names have changed

**Comment by davidlgj** [comment]
Hi @plong0 , I will merge this and #463 when the new builder is up and running. Soonish I hope :)

**Comment by plong0** [comment]
Sounds great @davidlgj!  Thanks, looking forward to it :)

**Comment by plong0** [comment]
made new PR #560 off development branch

**Pull request closed without merging**
