### PR TITLE
don't show has-success state until a field is dirty

### PR DESCRIPTION
**Pull request by cjroth**
This modifies the hasSuccess behavior to return true only when the field is dirty. See https://github.com/Textalk/angular-schema-form/issues/243#issuecomment-88175413

It would makes sense to add an option to show the hasSuccess when pristine too, if needed.

### CODE REVIEW

**Comment by davidlgj** [comment]
I can't merge this as it is since this breaks current behavior that at least we rely on.  But I do see the use case. What we need is for it to be optional. Probably with a global option and control per field level as well.

**Comment by cjroth** [comment]
Cool, that makes total sense. I'll add some options too.

**Comment by davidlgj** [comment]
Awesome :+1:

**Comment by shawnss** [comment]
Did this option get documented somewhere? I would like to use this as I do not want hasSuccess when form is rendered with existing data.

**Comment by Dervisevic** [comment]
@shawnss It isn't in there yet it seems. @cjroth Do you plan on adding the options?

**Comment by davidlgj** [comment]
@shawnss  I've started some work that incorporates this functionality, but as an option. https://github.com/Textalk/angular-schema-form/tree/hotfix/0.8.9

**Comment by davidlgj** [comment]
@shawnss @cjroth  I've added an new global option `pristine` that supports this. Hope that works for you.

**Pull request closed without merging**
