### PR TITLE
Added UMD wrapper for bootstrap-decorator

### PR DESCRIPTION
**Pull request by angelaharalson**
Fixes this issue:
 RequireJs wrapper for bootstrap-decorator #435

### CODE REVIEW

**Comment by nicklasb** [comment]
Interesting, I just made this PR:
https://github.com/Textalk/angular-schema-form/pull/493

:-)

**Comment by nicklasb** [comment]
I realized that this is way better than my PR, as it should require() everything properly.

**Comment by nicklasb** [comment]
While going on with packaging and modules, I should mention that I added ASF and some of the most used(?) ASF add-ons to the jspm registry:
https://github.com/jspm/registry/pull/510

**Comment by nicklasb** [comment]
#493 turned out to not be redundant after all. :-(

**Comment by davidlgj** [comment]
@angelaharalson awesome! I don't use RequireJS so I really appreciate help with this. Can I trouble you to redo the PR without the minified files in `dist`?

**Comment by davidlgj** [comment]
@angelaharalson I merged it manually since I want to migrate the decorator to it's own repo. Thanks!

**Comment by nicklasb** [comment]
Hi, this seems to be a problem with PR, I am however not sure what is the correct solution.
The problem is, that if one is using a module loading framework like SystemJS/JSPM or RequireJS, a dependency is on the "angular-schema-form"-form, as it is typically referring to a npm/bower/jspm registration, as you usually don't deviate from the naming, simply because one doesn't have to. 

This PR sets it to "schemaForm" for all situations, which does not work with those kinds of frameworks.

To make the component I am maintaining, [ngular-schema-form-dynamic-select](https://github.com/OptimalBPM/angular-schema-form-dynamic-select) work with my "MBE-frontend" which uses [SystemJS/JSPM](https://github.com/OptimalBPM/mbe-nodes/blob/master/example/static/jspm_config.js) and the names are automagically generated, I set the [amd and cjs options for the require](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/gulpfile.js#L61)-section. This way, loading bootstrap-decorator.js correctly causes angular-schema-form.js to load.

However, I am not completely sure about all of this, UMD and ES6 modules and their naming conventions and when what is used is a bit hard to understand and not always clear. So if someone more knowledgeable than me could chime in would be great.

**Comment by nicklasb** [comment]
@angelaharalson, @davidlgj : I feel pretty sure that the correct solution is:
```js
            dependencies: function() {
              return [
                {name: 'schemaForm',
                amd:"angular-schema-form",
                cjs: 'angular-schema-form'},
              ];
```

**Comment by nicklasb** [comment]
Aaand now something seems to be strange in gulp-umd. I'll be back.

**Pull request merged**
