### PR TITLE
fix validation inside ng-repeat

### PR DESCRIPTION
**Pull request by melnikaite**
#230

### CODE REVIEW

**Comment by davidlgj** [comment]
I've haven't had time to test it, just looked at the code, but do as I can see there is actually no check  that we are inside an ng-repeat? 

And relying on scope.$parent is a bit fragile, just introducing a directive in a template can break things. Hmmm... I don't know. I'll do some testing when I get the time.

**Comment by melnikaite** [comment]
Thanks for reply.
I also thought about option for providing scope that should be used instead of just using parent, because in some templates people can use more than one loop level, but unfortunately I don't have time to implement it.
So currently we can merge it as temporary solution.

**Comment by davidlgj** [comment]
Are there any other scenarios except the radios that you have found?

**Comment by melnikaite** [comment]
I haven't checked other templates with loops. Saw the problem only in radios and in my custom plugin that also use ng-repeat.

**Comment by davidlgj** [comment]
Hi @melnikaite I haven't done any testing yet, sorry. But today I finally got around fixing better validation messages and with that it was easy to fix the problems with radios type not validating. 

Basically the changes that have landed in the development branch today let's you use a the `schema-validate`directive on the each of the radios (it goes hand in hand with ngModel) and then project the error message from one of them to below the radios via a new `sf-message` directive. 

It would be super awesome if you have time to check it out and see if that solves it for your custom plugin as well. I've updated the "extending" docs a bit, but basically you add a `schema-validate` to each element with an `ngModel` on it and a `<div sf-messages="form.description">` where you want your error message to go.

**Comment by Dervisevic** [comment]
Has it solved the problem @melnikaite?

**Comment by melnikaite** [comment]
Yes, thanks a lot
It started working in my fiddle http://jsfiddle.net/mdmg0ad3/

**Pull request closed without merging**
